SportsStore_v1/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore_v1.Models;

namespace SportsStore_v1.Components {
    public class CartSummaryViewComponent : ViewComponent {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService) {
            cart = cartService;
        }
        public IViewComponentResult Invoke() {
            return View(cart);
        }
    }
}

SportsStore_v1/Components/NavigationMenuViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportsStore_v1.Models;

namespace SportsStore_v1.Components {
    public class NavigationMenuViewComponent : ViewComponent {
        private IProductRepository repository;
        public NavigationMenuViewComponent(IProductRepository repo) {
            repository = repo;
        }
        public IViewComponentResult Invoke() {

            ViewBag.SelectedCategory = RouteData?.Values["category"];
            
            if(RouteData?.Values["category"] == null){
                 ViewBag.Home = true;
            }
            return View(repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x)
            );
        }
    }
}

SportsStore_v1/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportsStore_v1.Infrastructure;
using SportsStore_v1.Models;
using SportsStore_v1.Models.ViewModels;

namespace SportsStore_v1.Controllers{
    public class CartController : Controller {
    private IProductRepository repository;
    private Cart cart;
    public CartController(IProductRepository repo, Cart cartService) {
        repository = repo;
        cart = cartService;
    }
    public ViewResult Index(string returnUrl) {
        return View(new CartIndexViewModel {
            Cart = cart,
            ReturnUrl = returnUrl
        });
    }
    public RedirectToActionResult AddToCart(int productId, string returnUrl) {
        Product product = repository.Products
            .FirstOrDefault(p => p.ProductId == productId);
        if (product != null) {
            cart.AddItem(product, 1);
        }
        return RedirectToAction("Index", new { returnUrl });
    }
    public RedirectToActionResult RemoveFromCart(int productId,
        string returnUrl) {
        
        Product product = repository.Products
            .FirstOrDefault(p => p.ProductId == productId);
        if (product != null) {
            cart.RemoveLine(product);
        }
        return RedirectToAction("Index", new { returnUrl });
    }
 }
}

SportsStore_v1/Views/Shared/ProductSummary.cshtml
@model Product
<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Name
            <span class="badge badge-pill badge-primary" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    <form id="@Model.ProductId" asp-action="AddToCart"
            asp-controller="Cart" method="post">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" name="returnUrl"
            value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Description
            <button type="submit"
                class="btn btn-success btn-sm pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

SportsStore_v1/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>@ViewBag.Title</title>
    <script src="/lib/jquery/dist/jquery.min.js"></script>
    <script src="/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script
        src="/lib/jquery.validate.unobtrusive.min.js">
    </script>
    <style>
        .input-validation-error { border-color: red; background-color: #fee ; }
    </style>
</head>
<body class="m-1 p-1">
    <div class="bg-info p-2"><h4>@ViewBag.Title</h4></div>
    @if (TempData["message"] != null) {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</body>
</html>

SportsStore_v1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
        asp-href-include="/lib/bootstrap/dist/**/*.min.css"
        asp-href-exclude="**/*-reboot*,**/*-grid*" />
     <link rel="stylesheet" asp-href-include="/lib/css/*.css" />

    <title>Shopstore</title>
</head>
<body>

    <nav class="navbar navbar-dark bg-dark" role="navigation">
        <a class="navbar-brand" href="/">SPORTS STORE</a>
        <ul class="navbar-nav">
            <li class="nav-item active">
                @await Component.InvokeAsync("CartSummary")
            </li>
        </ul>
    </nav>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
             @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>